# Generated by Django 3.1.3 on 2020-11-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresults',
            name='movie_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='searchresults',
            name='movie_location',
            field=models.CharField(default='', max_length=2083, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='searchresults',
            name='movie_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
