# Generated by Django 3.1.3 on 2020-11-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201113_1941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchResult',
        ),
    ]
