# Generated by Django 3.1.3 on 2020-11-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_searchresults'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchResults',
            new_name='SearchResult',
        ),
    ]
