# Generated by Django 3.1.3 on 2020-11-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201114_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchResult',
        ),
    ]
