# Generated by Django 3.1.3 on 2020-11-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201114_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventresult',
            old_name='img',
            new_name='image',
        ),
    ]
