# Generated by Django 3.1.3 on 2020-11-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201114_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMVenuesResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=2083)),
                ('image', models.CharField(max_length=2083)),
            ],
        ),
    ]
